<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise</title>
  <script src="./js/MyPromise.js"></script>
  <script>
// new promise 构造执行 输出 "最外侧 promise"  -> resolve 执行完 -> 执行外部第一个then 
    // 外部第一个then 返回了 一个 promise ，这个 return 代表外部第二个then 需要等待 return 之后 promise的结果
    // 所以内部的 promise 都是优先 外部第二个then 执行完
    /**
     * 同一个promis 可以有多个 then(), 按先后顺序依次触发
     * 如果 then 中存在 return promise 则会等待promis执行完
     * 
     */
    // new Promise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve()
    // }).then(() => { // 外部第一个then
    //   console.log("外部第一个then")
    //   return new Promise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     setTimeout(() => {
    //       console.log("内部 promise setTimeout")
    //       resolve()
    //     }, 1000)
    //   }).then(() => {
    //     console.log("内部第一个then")
    //   }).then(() => {
    //     console.log("内部第二个then")
    //   })
    // }).then(() => { // 外部第二个 then
    //   console.log("外部第二个then")
    // })
    // 第二种表现
    // new Promise((resolve, reject) => {
    //   // Promise的 构造函数 入参数函数 是 同步执行的
    //   console.log("最外侧 promise")
    //   resolve()
    // }).then(() => { // 外部第一个then
    //   new Promise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     resolve()
    //   }).then(() => {
    //     console.log("内部第一个then")
    //   }).then(() => {
    //     console.log("内部第二个then")
    //   })
    // }).then(() => { // 外部第二个 then
    //   console.log("外部第二个then")
    // })
    // 第三种表现
    // new Promise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve()
    // }).then(() => { // 外部第一个then
    //   let p = new Promise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     resolve()
    //   })
    //   p.then(() => {
    //     console.log("内部第一个then")
    //   })
    //   p.then(() => {
    //     console.log("内部第二个then")
    //   })
    // }).then(() => { // 外部第二个 then
    //   console.log("外部第二个then")
    // })

    // 第四种表现
    // let p = new Promise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve()
    // })
    // p.then(() => { // 外部第一个then
    //   new Promise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     resolve()
    //   }).then(() => {
    //     console.log("内部第一个then")
    //   }).then(() => {
    //     console.log("内部第二个then")
    //   })
    // })
    // p.then(() => { // 外部第二个 then
    //   console.log("外部第二个then")
    // })

    // 第五种情况
    // new Promise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve()
    // }).then(() => { // 外部第一个then
    //   new Promise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     resolve()
    //   }).then(() => {
    //     console.log("内部第一个then")
    //     return Promise.resolve()
    //   }).then(() => {
    //     console.log("内部第二个then")
    //   })
    // }).then(() => { // 外部第二个 then
    //   console.log("外部第二个then")
    // }).then(() => {
    //   console.log("外部第三个then")
    // })
    


    // promise 终极面试题 分析
    // const promisetemp = new Promise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve(4)
    // })
    
    Promise.resolve().then(() => {
        console.log(0)
        // 这里是关键 如何理解
        // return Promise.resolve('4') 等效下面
        const Pnew = new Promise((resolve, reject) => {
          resolve(4)
          // console.log('P0 内部Promise resolve 只是完成了状态变动')
        })

        // 状态塌陷，v8 引擎 分为 准备， 吸收 两部，且 都是放在微任务中执行
        return Pnew // 这里的promise 是一个 pending 状态的 promise 且自动调用 then 函数 -> 又产生一个 promise
    })
    .then((res) => {
      console.log(res)
    })

    
    // Promise.resolve({then: function(resolve, reject) {
    //   console.log('res')
    //   resolve('cgt')
    //   // return 'cgt'
    // }}).then(res => {console.log(res)})
      
    Promise.resolve().then(() => {
        console.log(1)
      })
      .then(() => {
        console.log(2)
      })
      .then(() => {
        console.log(3)
      })
      .then(() => {
        console.log(5)
      })
      .then(() => {
        console.log(6)
      })
    console.log("主线程执行结束")
  </script>
  <script>
    console.log("mypromise demo start")
    // 自定义的 promise 测试
    // PROMISE 异步的异常是捕获不到的，无法影响 promis 的状态

    const p = new MyPromise((resolve, reject) => {
      // setTimeout(() => {
      //   reject(222);
      // }, 1000);
      resolve(111)
    })


    p.then(123, (err)=>{
      console.log('promise 失败1', err);
      return err
    }).then(res => {
      console.log('最后一个 promise 结果 来自第一个 透传而来',res)
      console.log('promise 完成1',res)
      return res
    })
    // 二次 订阅
    p.then(res => {
      console.log('promise 成功2',res)
      return res // 这里是否return 不影响流程 但 子then 的返回值是 undefined
    }, (err) => {
      console.log('promise 失败2 订阅二', err);
      return err // 这里是否return 不影响流程 但 子then 的返回值是 undefined
    }).then(res => {  
      console.log('then2-2 ',res) // undefined
      return res // 尾部不返回 将有一个 undefined
    })
    // let p = new MyPromise((resolve, reject) => {
    //   console.log("最外侧 promise")
    //   resolve()
    // })
    // p.then(() => { // 外部第一个then
    //   let p = new MyPromise((resolve, reject ) => {
    //     console.log("内部 promise");
    //     resolve()
    //   })
    //   p.then(() =>{})
    // })
    // p.then((res) => {
    //   console.log(p.handlers, 'res', res)
    //   return new Promise((ref, rej) => {
    //     console.log('我的插入promise 但一直未完成')
    //     console.log(p.handlers, 'aaa')
    //     setTimeout(() => {
    //       console.log('我的插入promise 马上结束')
    //       ref(res)
    //     }, 1000);
    //   })
    // }, (err) => {
    //   console.log('promise 失败1', err);
    //   // return 456
    // })
    //   .then((res) => {
    //     console.log('插入的 promise 成功', res)
    //     return res
    //   }, (err) => { })
    // p 多次调用 then 此时 应该出现 多个 #handles？？
    // p.then((res) => {
    //   console.log('promise 完成1-2',res)
    // },(err) => {
    //   console.log('promise 失败1-2', err);
    // })
    // p.then((res) => {
    //   console.log('promise 完成2',res);
    // }, (err) => {
    //   console.log('promise 失败2', err);
    // })
    // p.then((res) => {
    //   console.log('promise 完成3',res);
    // }, (err) => {
    //   console.log('promise 失败3', err);
    // })
    // p.then((res) => {
    //   console.log('promise 完成4',res);
    // }, (err) => {
    //   console.log('promise 失败4', err);
    // })

  </script>
</head>

<body>
  <h1>promice</h1>
</body>

</html>